### ISSUE TITLE
displaying all finals makes browser lag and crash on slower devices

### ISSUE THREAD

**Issue by bmiddha** [bmiddha/final-countdown#7]
Add a configurable limit on how many final countdowns are displayed at once.
Displaying too many makes the browser slow.

**Comment by halfnibble** [comment]
One library I recommend to handle this is "react-virtualized"
https://bvaughn.github.io/react-virtualized/#/components/Grid

**Comment by bmiddha** [comment]
Added an option in `Config.ts` to change how many finals are shown.
